version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5433:5432'